frontend:
  build: ./frontend
  restart: always
  links:
    - backend:backend
  ports:
    - "80:80"
backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
